service: fcom-sso

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  authorize:
    handler: handler.authorize
    events:
      - http:
          path: authorize
          method: get

  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: get

  loginPost:
    handler: handler.postLogin
    events:
      - http:
          path: login
          method: post
